let rules = new Map()
rules.set('001', {carryNecessary: true})
rules.set('011', {carryNecessary: false})
rules.set('201', {carryNecessary: false})
rules.set('101', {carryNecessary: false})
rules.set('000', {carryNecessary: false})
rules.set('010', {carryNecessary: false})
rules.set('100', {carryNecessary: false})
rules.set('200', {carryNecessary: false})
export default rules
